### ISSUE TITLE
How to implement angular-google-maps?

### ISSUE THREAD

**Issue by luisgithub** [jakemmarsh/angularjs-gulp-browserify-boilerplate#138]
Hi, I'am not an expert on angular, can you give me an idea of how to add angular-google-maps set of directives to my angular-gulp-browserify-boilerplate project?, I am not really sure of what files need to change to enable it. I'll really appreciate if you can show me an example of an implementation..

**Comment by jakemmarsh** [comment]
This isn't really an issue with the boilerplate, but I'll try to give you some general directions.

First of all, they provide documentation and a quickstart guide for that project [here](http://angular-ui.github.io/angular-google-maps/#!/use). That should cover most of what you're looking for.

First, you need to install the project via npm or bower. I personally tend towards npm, so `npm install --save-dev angular-google-maps`. Then you need to either load that script in your `app/index.html` as mentioned in that quickstart guide, or require it within your actual javascript with `import 'angular-google-maps';`. (Note, we're not aliasing it as anything because the project doesn't export anything. It will be loaded globally/on the window).

From there, you need to add `'uiGmapgoogle-maps'` to the array of requires in `app/js/main.js`. From there, you should be able to use the project and its features as expected.

**Comment by luisgithub** [comment]
Thanks a lot, I was missing to add 'uiGmapgoogle-maps' to requires in
main.js. now, I am facing a situation with a controller, I just copy the
controllers/example.js an rename to controllers/map.js with the original
code:

/**
 * Created by luis on 1/14/16.
 */
function MapController() {

    // ViewModel
    const vm = this;

    vm.title = 'AngularJS, Gulp, and Browserify! Written with keyboards and
love!';
    vm.number = 1234;

}

export default {
    name: 'MapController',
    fn: MapController
};

and then I changed the on_config.js file like this:

function OnConfig($stateProvider, $locationProvider, $urlRouterProvider) {
  'ngInject';

  $locationProvider.html5Mode(true);

  $stateProvider
  .state('Home', {
    url: '/',
    controller: 'MapController as map',
    templateUrl: 'home.html',
    title: 'Home'
  });

  $urlRouterProvider.otherwise('/');

}

export default OnConfig;

And Chrome console is throwing me this error:
Regex
Hide network messages
- All
- Errors
- Warnings
- Info
- Logs
- Debug
- Handled
.

   1. angular.js:12520 Error: [ng:areq] Argument 'MapController' is not a
   function, got undefined


Any idea to fix this error?


Thanks Again...


2016-01-14 12:21 GMT-07:00 Jake Marsh <notifications@github.com>:

> This isn't really an issue with the boilerplate, but I'll try to give you
> some general directions.
>
> First of all, they provide documentation and a quickstart guide for that
> project here <http://angular-ui.github.io/angular-google-maps/#!/use>.
> That should cover most of what you're looking for.
>
> First, you need to install the project via npm or bower. I personally tend
> towards npm, so npm install --save-dev angular-google-maps. Then you need
> to either load that script in your app/index.html as mentioned in that
> quickstart guide, or require it within your actual javascript with import
> 'angular-google-maps';. (Note, we're not aliasing it as anything because
> the project doesn't export anything. It will be loaded globally/on the
> window).
>
> From there, you need to add 'uiGmapgoogle-maps' to the array of requires
> in app/js/main.js. From there, you should be able to use the project and
> its features as expected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/issues/138#issuecomment-171750278>
> .
>



-- 
Ing. Luis Garcia
