### ISSUE TITLE
ng-app, ng-controller declaration missing

### ISSUE THREAD

**Issue by udayms** [jakemmarsh/angularjs-gulp-browserify-boilerplate#145]
Hi,

Apologize if this is too stupid. But, I just realized that the index.html doesnt have a ng-app anywhere in it. I also searched the whole project and couldn't find any ng-app declaration in the DOM.

Also, my controllers are working without ng-controller. 

How does this work?

**Comment by jakemmarsh** [comment]
Instead of an `ng-app` directive, we're manually bootstrapping the application onto the document in `main.js`: https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/app/js/main.js#L33

Instead of `ng-controller` directives, we're specifying a controller for each individual route in the application in `on_config.js`: https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/app/js/on_config.js#L9

**Comment by udayms** [comment]
Thanks @jakemmarsh for this clarification. It was helpful.
