### ISSUE TITLE
Any examples of how to use Primus/Socket.io with this?

### ISSUE THREAD

**Issue by varmint09** [jakemmarsh/angularjs-gulp-browserify-boilerplate#17]

**Comment by jakemmarsh** [comment]
I personally don't have any experience with Primus, but using a [library like this](https://www.npmjs.com/package/primus.io) may be helpful. You could `npm install` and require it via Browserify, then use the Client-side directions from that repo.

**Comment by varmint09** [comment]
I have an issue with browsersync, what would the most elegant way be to enable or disable it?

perhaps something in gulp/config.js ? care to suggest what might be needed!

**Comment by jakemmarsh** [comment]
I don't think I'll add this to the boilerplate, but you could wrap the `browserSync` task like so:
```
if ( config.useBrowserSync ) {
    browserSync({
      proxy: 'localhost:' + config.serverport
    });
  }
```

then in `config.js` add a simple flag like so:
```
'useBrowserSync': false
```

I just pushed a commit (495236d633342eb202ce0c98dc75d43ec56e9b15) that should prevent any bugs/errors if you add this flag. Just note that if you add that flag and opt not to use browserSync, your app will be at `localhost:3000` rather than the `localhost:3001` proxy.
