### ISSUE TITLE
Environment AppSettings

### ISSUE THREAD

**Issue by bpalermo** [jakemmarsh/angularjs-gulp-browserify-boilerplate#187]
Hi,

Would be possible to generate different AppSettings for dev and production based on the gulp task?

Thanks,
Bruno

**Comment by jakemmarsh** [comment]
You could add [envify](https://github.com/hughsk/envify) to the [Browserify transforms](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/gulp/tasks/browserify.js#L39) to inject a specified environment into anywhere in your code that references `process.env.NODE_ENV`, then have conditionals like so in your app settings:

```js
const AppSettings = {
  appTitle: 'Example Application',
  apiUrl: process.env.NODE_ENV === 'production' ? '/api/v1' : 'localhost:3000/api/'
};

export default AppSettings;
```

**Comment by bpalermo** [comment]
If I understand it right, it would work if I'm running o nodejs, right? But what if I'm hosting a static website in AWS S3 for example?

**Comment by jakemmarsh** [comment]
Since `envify` would be a `browserify` transform executed during the build step, it converts all instances of `process.env.NODE_ENV` into a string literal determined by the `NODE_ENV` option you pass to `envify`:

```js
b.transform(envify({
  NODE_ENV: 'development'
}))
```

This means it would work just fine on a static site, since all references to the actual environment variable are removed.

**Comment by bpalermo** [comment]
Many thanks I will give it a try.
