### ISSUE TITLE
Using the new angular component

### ISSUE THREAD

**Issue by mangopop** [jakemmarsh/angularjs-gulp-browserify-boilerplate#199]
I've tried to use the new component module by swapping out the directive index.js with this

js/components/index.js

     //import angular from 'angular';

    const bulk = require('bulk-require');
    const componentsModule = angular.module('app.components', []);
    const components = bulk(__dirname, ['./**/!(*index|*.spec).js']);

    function declare(controllerMap) {
    Object.keys(controllerMap).forEach((key) => {
        let item = controllerMap[key];

        if (!item) {
            return;
        }

        if (item.fn && typeof item.fn === 'function') {
            componentsModule.controller(item.name, item.fn);
        } else {
            declare(item);
        }
    });
    }

    declare(components);

    export default componentsModule;

and this implementing the component as thus

js/components/testComponent.js

    function TestComponent() {

    return {
        template: '<span>Name: {{$ctrl.hero.name}}</span>',
        controller: function () {
        },
        bindings: {
            hero: '='
        }
    };
    }

    export default {
    name: 'test',
    fn: TestComponent
    };

view.html
`<test hero="ctrl.hero">component not working</test>`

But after importing and requiring into the module I'm not getting the component to show? 

Just seeing 'component not working' .

Directive working just fine alongside it.

Anyone successfully done this? I didn't think it would be an issue , there may be some error in the way I've implemented it?

I'm using Angular 1.5.6 

Thanks

**Comment by ppallesws** [comment]
I see two major problems with this approach.  

1. componentsModule.controller(item.name, item.fn);  -  In this line you're declaring the controller, not the component.  Instead of componentsModule.directive(item.name, item.fn); you probably want to use something like this: componentsModule.component(item.name, item.fn);

2. Second, Components are not the same format as Directives. For this to two you'll need to replace your directive code with something like this (notice the subtle differences).  Use an object instead of a function:

const TestComponent = {
    template: '<span>Name: {{$ctrl.hero.name}}</span>',
    controller: function () {
    },
    bindings: {
        hero: '='
    }
}

export default {
name: 'test',
obj: TestComponent
};

**Comment by ppallesws** [comment]
Here is an example: https://github.com/ppallesws/angularjs-gulp-browserify-boilerplate/tree/master/app/js/components

**Comment by mangopop** [comment]
Thanks very much for the example, got it working now.
