### ISSUE TITLE
Question: Why is there a need for expressjs server

### ISSUE THREAD

**Issue by joey-ecal** [jakemmarsh/angularjs-gulp-browserify-boilerplate#33]
Why do we need to launch the app from an expressjs server if we can just use browserSync to serve files from build directory?

**Comment by jakemmarsh** [comment]
Currently, Express is used because we need some custom routing configuration to use the client-side routing up to AngularJS (and serving all other files as static).

AFAIK, this isn't possible with browser-sync but I could very well be wrong. If you want to look into removing the Express dependency, that'd be great!

**Comment by p0o** [comment]
@jakemmarsh Do we need the express configuration in the production version too? Is it for HTML5 routing (no hash URLs) or something else?

**Comment by jakemmarsh** [comment]
@p0o currently, the server logic is only set up to be run via gulp. It's assumed that you have a server configuration of your own for your production app. However, the same logic could be used for a standalone node/express server (yes, it is set up for HTML5 routing without hashes)

**Comment by jakemmarsh** [comment]
Removed the separate server in 417c4decd2d920b457f1f13236bbf550164aee8a

**Comment by karneaud** [comment]
@p0o Did this work for you?

**Comment by p0o** [comment]
@karneaud What exactly? I didn't have any problem of working with this rep before.

**Comment by karneaud** [comment]
see issue #177 Seems I'm having trouble with protractor when using an additional server
