### ISSUE TITLE
Directives with templateURL

### ISSUE THREAD

**Issue by UsainBloot** [jakemmarsh/angularjs-gulp-browserify-boilerplate#35]
Hey, I am slightly confused as to how I am supposed to create a directive that uses a templateURL.
I currently have a structure of /views/templates/directiveItem.html

But every time I reference that it just returns the http://localhost:3001 index.html.

Would I have to create routes for each directiveItem and if could you please give me an example?

**Comment by jakemmarsh** [comment]
The problem is that you're referencing a template file that doesn't actually exist in the build directory. The gulp `views` task concatenates all html files, converting them to Javascript, which is later included in the Browserify task.

Have you tried doing a non-relative templateURL, like it's done [in routes.js](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/app/js/routes.js#L14)? In your example, it would just be `directiveItem.html` I believe.

**Comment by varmint09** [comment]
Is this not connected to the same issue we found with browserify? :)

**Comment by UsainBloot** [comment]
@jakemmarsh, I attempted to setup a route for the templateURL but it didn't seem to work, it may be just because I'm new to Angular anyway. Maybe I should just configure the build to include a /views/templates/ folder.

**Comment by UsainBloot** [comment]
Took the wrong approach with this one.
Solved the issue by wrapping the `targetUrl` with `require()` like so.

`templateUrl: require('path/to/file.html')`

**Comment by jakemmarsh** [comment]
Glad you were able to solve it, thanks for the update! :+1:

**Comment by philglen** [comment]
Hey Usain,

I am having the same issue, so tried wrapping my templateUrl, in routes.js, path to template with require but Gulp spits out an error saying it cannot find the module.

I have the path correct so I'm confused, I too am still inly getting index.html loaded up.

Did you have to modify any other files?

**Comment by UsainBloot** [comment]
@philglen, I have updated my comment above, i meant to say `template` instead of `templateUrl`. Hope this helps!
