### ISSUE TITLE
Old Jasmine

### ISSUE THREAD

**Issue by androidfred** [jakemmarsh/angularjs-gulp-browserify-boilerplate#39]
This project is awesome. I'd like to use a more recent version of Jasmine though. I tried changing this line in package.json from
```
"karma-jasmine": "^0.1.5",
```
to
```
"karma-jasmine": "^0.2.0",
```
as laid out in https://www.npmjs.com/package/karma-jasmine and then doing an npm install, but once thats done the tests no longer run. I've been trying but can't figure out why, any help would be much appreciated.

**Comment by jakemmarsh** [comment]
I tried updating to karma-jasmine 0.3.5 (and also added the new karma-core dependency in 0.3.x), and my unit tests are no longer passing either.

For some reason, it can no longer successfully mock the app via `angular.mock.module('app')` in the tests. This means a module somewhere is failing to load. Unfortunately, I'm unable to replicate it in the actual application (still builds and runs fine).

Any similar problems found via Google are mostly related to `ng-route`, but this boilerplate uses `ui-router` instead so that shouldn't be the issue. This is the specific error occurring: https://docs.angularjs.org/error/$injector/modulerr?p0=app&p1=Error:%20%5B$injector:nomod%5D%20http:%2F%2Ferrors.angularjs.org%2F1.3.15%2F$injector%2Fnomod%3Fp0%3Dapp%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20http:%2F%2Flocalhost:9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.min.js%3Fc8470371db8d3735604343a9a059002d3a827663:6:417%0A%20%20%20%20at%20http:%2F%2Flocalhost:9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.min.js%3Fc8470371db8d3735604343a9a059002d3a827663:21:412%0A%20%20%20%20at%20a%20(http:%2F%2Flocalhost:9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.min.js%3Fc8470371db8d3735604343a9a059002d3a827663:21:53)%0A%20%20%20%20at%20http:%2F%2Flocalhost:9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.min.js%3Fc8470371db8d3735604343a9a059002d3a827663:21:296%0A%20%20%20%20at%20http:%2F%2Flocalhost:9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.min.js%3Fc8470371db8d3735604343a9a059002d3a827663:35:116%0A%20%20%20%20at%20r%20(http:%2F%2Flocalhost:9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.min.js%3Fc8470371db8d3735604343a9a059002d3a827663:7:302)%0A%20%20%20%20at%20g%20(http:%2F%2Flocalhost:9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.min.js%3Fc8470371db8d3735604343a9a059002d3a827663:34:399)%0A%20%20%20%20at%20Object.ab%20%5Bas%20injector%5D%20(http:%2F%2Flocalhost:9876%2Fbase%2Fnode_modules%2Fangular%2Fangular.min.js%3Fc8470371db8d3735604343a9a059002d3a827663:38:135)%0A%20%20%20%20at%20Object.workFn%20(http:%2F%2Flocalhost:9876%2Fbase%2Fnode_modules%2Fangular-mocks%2Fangular-mocks.js%3Fbd422b0634824fd1aec4b70bdad3b63fc7e1f519:2425:52

**Comment by sksadri** [comment]
I had the same issue! replaced jasmine with mocha and now tests work again

**Comment by ppallesws** [comment]
Has anyone made any progress upgrading to Jasmine 2.x or understand why this throws errors on angular.mock.module?

**Comment by jakemmarsh** [comment]
This was related to the use of `angular.element(document).ready` when instantiating the app. Updated in 8df9fe1a0e5652ebeab7e997c701054cc212f3aa
