### ISSUE TITLE
bower / npm conflict?

### ISSUE THREAD

**Issue by varmint09** [jakemmarsh/angularjs-gulp-browserify-boilerplate#46]
Hello,

If I use something like; https://github.com/angular-ui/bootstrap which I install with bower, it also includes angular and installs it, so then i have a copy of angular in node_modules and another in bower_modules and then it breaks.

If I remove angular from the node_modules folder, then the app doesnt start either, and it does seem that most bower components I wanted to use, also install angular.

Any ideas on a solution, ideally one I can port back into my copy of this fine boilerplate.

**Comment by jakemmarsh** [comment]
Unfortunately, I don't know of any solutions to this problem. The two package managers have no knowledge of each other, so redundant dependencies is unavoidable as far as I know. My only solution would be to manually download and include the library rather than using Bower. A similar issue was discussed in #20

**Comment by hoodsy** [comment]
Has anyone found a good solution for this? Even including angular locally causes problems, as other dependencies look for angular in node_modules from what I have seen.

**Comment by esouto** [comment]
I've tried to add the "dist" folder content of the bower package manually inside "js/third_party" folder and add the styles inside "styles" folder to get them from gulp.
This is a kind of solution for me, not the optimal but at least one.

I'm trying to use bower mainly for for bootstrap angular components.

**Comment by victmo** [comment]
For this specific package (ng ui bootstrap) try using NPM instead of bower.

Ideally you want to avoid using bower at all.

angular-ui-bootstrap depends on angular-animate and bootstrap (or bootstrap-sass), so install all of them.

```
$ npm install angular-ui-bootstrap angular-animate bootstrap-sass --save
````

then add bootstrap to your main.scss

```sass
@import '../../node_modules/bootstrap-sass/assets/styles/bootstrap/_bootstrap.scss'
```

and to your main.js

```js
require('angular-animate');
require('angular-ui-bootstrap');
...
angular.module('app', ['ngAnimate', 'ui.bootstrap', ... ]);
```

It'll be nice to be able to add sass' `includePaths` in the config. I'll create a new issue with this suggestion.

**Comment by StrikeForceZero** [comment]
@varmint09 @jakemmarsh @hoodsy @esouto 

To get angular to load from bower instead of npm add the following to your package.json and ```npm install browserify-shim --save```

My [package.json](https://github.com/StrikeForceZero/angularjs-cordova-gulp-browserify-boilerplate/blob/master/package.json)

```
"browser": {
    "angular": "./bower_components/angular/angular.js",
    "jquery": "./bower_components/jquery/dist/jquery.js"
  },
  "browserify-shim": {
    "angular": "angular",
    "jquery": "$"
  },
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  }
```

**Comment by jakemmarsh** [comment]
Ah right, that's a good solution! Thanks @StrikeForceZero. That will work, although I would still personally advise against using Bower components if at all possible to avoid extra steps like this.
