### ISSUE TITLE
Routing Resolves : Reference to resolve property

### ISSUE THREAD

**Issue by Izcalli** [jakemmarsh/angularjs-gulp-browserify-boilerplate#54]
Since [angularjs styleguides](https://github.com/toddmotto/angularjs-styleguide#routing-resolves) tells us :
> Never bind logic to the router itself. Reference a `resolve` property for each Controller to couple the logic

How can we refer to the controller's `resolve` property in on_config.js ?

Thank you

**Comment by jakemmarsh** [comment]
In the modular way that the project is currently configured, I believe you only have two options for a route `resolve`:

- Explicitly define the resolve function within `on_config.js`, like so:
```
$routeProvider
  .when('/', {
    templateUrl: 'main.html',
    controller: 'MainCtrl as main',
    resolve: {
      doSomething: function () {
        // do your promise-based resolve logic here
      }
    }
  });
```
- Somehow import the controller via a `require` statement so that you can access it and its properties (this would probably be the messier solution). That'd look something like:
```
var yourController = require('./controllers/example');
$routeProvider
  .when('/', {
    templateUrl: 'main.html',
    controller: 'MainCtrl as main',
    resolve: yourController.resolve
    }
  });
```
