### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by dam4222** [jakemmarsh/angularjs-gulp-browserify-boilerplate#60]
Hey Jake,

I am sort of a newbie to all of this so please excuse me if I am asking a dumb question. I used your amazing boilerplate to build a portfolio for myself. You can find it here: https://github.com/dam4222/adamperlis.com

I am trying to get this up an running on Heroku and so far I have failed every time despite following there instructions.

Any chance you can take a look and see where I am going wrong? Would be awesome to contribute these steps in your readMe for people in the future as well!

Thanks,
Adam

**Comment by jakemmarsh** [comment]
I feel this is a bit outside the scope of the boilerplate, but I'll try my best to help you get it up and running on Heroku.

First of all, you removed your `index.js` server file in your last commit? You're going to need that file to function as your server on Heroku. Additionally, you should modify it to serve your files from the `/build` directory instead of `/public`, so that it's serving your compiled application.

In order to ensure that your `/build` directory exists upon/after deploy to Heroku, you're either going to have to remove it from the gitignore and compile your app pre-deploy, or add a `postinstall` npm script that runs `gulp prod`. If you choose the latter, all the devDependencies will now be required as normal dependencies (since that's all that Heroku installs). It looks like you've completely duplicated your dependencies, but really you can remove the devDependencies if you go with the latter route.

**Comment by dam4222** [comment]
Hey Jake,

This is super helpful! I realize that it is a bit outside scope. So thank you so much for your kind response. Hopefully someone else will benefit from it as well.

Adam

**Comment by jakemmarsh** [comment]
No problem! I'm going to close this issue, but let me know if you have any further troubles/questions

**Comment by dam4222** [comment]
Hey Jake,

So I wanted to give this my best shot on my own before coming back to you. Here is what I did, I created a server like you suggested as index.js which looks like this:

var express = require('express');
var app = express();

app.set('port', (process.env.PORT || 5000));

app.use(express.static(__dirname + '../build'));

// views is directory for all template files
app.set('views', __dirname + '../build');
app.set('view engine', 'html');

app.get('/', function(request, response) {
  response.render('index.html');
});

app.listen(app.get('port'), function() {
  console.log('Node app is running on port', app.get('port'));
});

However, I am having trouble understanding all of the pieces here as they are new to me. The error I receive when I deploy this to heroku is as follows:

Error: Cannot find module 'html'
   at Function.Module._resolveFilename (module.js:336:15)
   at Function.Module._load (module.js:278:25)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
   at new View (/app/node_modules/express/lib/view.js:78:30)
   at EventEmitter.render (/app/node_modules/express/lib/application.js:569:12)
   at ServerResponse.render (/app/node_modules/express/lib/response.js:961:7)
   at /app/index.js:13:12
   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
   at next (/app/node_modules/express/lib/router/route.js:131:13)

Any ideas?

**Comment by jakemmarsh** [comment]
I'm not sure what you're doing with the `app.set('views'...` and `app.set('view engine'...`. You should be able to pretty much copy all of the code from [gulp/tasks.server.js](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/gulp/tasks/server.js) to serve as your index file. That file does exactly what you're trying to do, running an Express server that serves your application and any necessary assets. It's just wrapped in a Gulp task to only run while developing, but the logic would remain the same.

**Comment by dam4222** [comment]
Hi Jake,

Thanks again for all your help with this. I attempted what you suggested. You can have a look at the my index.js here: https://github.com/dam4222/adamperlis.com/blob/master/index.js

I just removed the gulp task and left everything else the same.

Still having the same problems but different errors. Have you had success getting it up on the running on Heroku? Maybe I am missing something?

Thanks again.

Adam

Adam

**Comment by jakemmarsh** [comment]
It would be helpful to see what the actual errors are that you're getting. Does the server run locally? I wouldn't bother with Heroku until it is. To test this, just run `node index.js` from your project root

**Comment by dam4222** [comment]
Hey Jake, I figured it out! You were correct the server wasn't functioning properly locally. Additionally, I noticed that angular-animate had somehow been removed from the package.json as well as my scripts and was causing a errors. For the benefit of others here is a working server you can place into your root as well as the scripts you should place into the package json:


/////////* index.js *////////////
	var express = require('express');
	var http    = require('http');
  var server = express();

  server.set('port', (process.env.PORT || 5000));

  // log all requests to the console
  server.use(express.static('build'));

  // Serve index.html for all routes to leave routing up to Angular
  server.all('/*', function(req, res) {
      res.sendFile('index.html', { root: 'build' });
  });

  // Start webserver if not already running
  var s = http.createServer(server);
  s.on('error', function(err){
    if(err.code === 'EADDRINUSE'){
      gutil.log('Development server is already started at port ' + server.get('port'));
    }
    else {
      throw err;
    }
  });

  s.listen(server.get('port'), function() {
  	console.log('Node app is running on port', server.get('port'));
	});

/////////* place this into your package.json *////////////

 "scripts": {
        "postinstall": "gulp prod",
        "start": "node index.js"
    },

******move devDependencies to Dependencies.


Not sure if this is necessary but I added this buildpack by typing this into the terminal:
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs#v75 -a my-app

**Comment by jakemmarsh** [comment]
Good to hear, glad you got it working! Thanks for the little write-up as well.

**Comment by pascal08** [comment]
@dam4222 I'm trying to deploy my app to Heroku too. I used your snippet to successfully build my app with Heroku (I hope you don't mind :) ). When I open that Heroku's app URL (https://assignment-editor.herokuapp.com/) I can see that my app is not working properly and the following errors spawn in my console:

Uncaught SyntaxError: Unexpected token < 
*angular-bootstrap-validation.js:1*

Uncaught Error: [$injector:modulerr] Failed to instantiate module xmlFormEditorApp due to:
Error: [$injector:unpr] Unknown provider: e
*main.js:2*

What I've tried so far to get this to work:
 - I've created a Procfile containing: "web: node index.js"
 - I've executed the commands in the Readme of this repo: https://github.com/krry/heroku-buildpack-nodejs-gulp-bower

As I mentioned before, no errors show up during Heroku's deployment process. Besides that, my app works just fine when I'm running 'gulp dev'.

Does anybody know how I can fix this?

*I'm sorry if I should not have posted this here (old issue)*

Btw, great boilerplate! Keep up the good work. :+1:
