### ISSUE TITLE
Bower installation issue

### ISSUE THREAD

**Issue by esouto** [jakemmarsh/angularjs-gulp-browserify-boilerplate#66]
I'm trying to install "bower install angular-pretty-checkable --save" that actually contains a dependency on angular, so this trigger an error.
I don't have a "third party" folder to at least add the js/css files into the project. I can add a filter inside js folder and another inside styles and this will be compiled, but that's not the idea.
I like to at least process the "dist" folder that came on the bower package and be able to install it as --production to avoid the angular bower dependency install.

What's your recommendation on this?
What kind of bower packages are supposed to install in this boilerplate?

![image](https://cloud.githubusercontent.com/assets/302908/9570440/581a90dc-4f62-11e5-9e98-c6c90ade8860.png)

Thanks in advance for your help.
Eduardo

**Comment by jakemmarsh** [comment]
This same issue has been discussed a few times (#20, #46) and no solid solution has been found. Any bower components that have Angular as a dependency will attempt to install their own local version, thus conflicting with the NPM version installed by default.

As of now, the only solution I know of would be to manually include the bower component files rather than attempting to `require` them via debowerify.

Closing in favor of #46

**Comment by esouto** [comment]
Thank you so much for this quick answer.
