### ISSUE TITLE
Beginner question regarding ExampleService

### ISSUE THREAD

**Issue by Miramac** [jakemmarsh/angularjs-gulp-browserify-boilerplate#76]
I wonder why the "ExampleService" is invoked as a service
and not as a factory? 
````
servicesModule.service ('ExampleService', ExampleService);
````
I use this great project as a patter for my angular project. But I previously understood the difference between between service and factory the other way.

thanks!

**Comment by jakemmarsh** [comment]
The main difference is that a factory will return the value returned by invoking the factory function, while a service returns an instance of the service function. Since they are both singletons, I don't think there is any huge difference between the two for this use case. To me, a factory might be more useful when returning something like a class function for creating new instances.
